### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by behrisch** [mschrader15/sumo-pipelines#11]
Hi Max,
thank you for providing this! We were thinking about incorporating it in our own calibrations but we need to check licensing before that. Could you add an MIT (or similar thing) to this package as well?

Thank you!

**Comment by mschrader15** [comment]
Hey @behrisch, cool to see that you found this! I've added an MIT License. 

I wrote this as the sole user, so its sparsely documented and likely contains bugs. I'll be happy to review any PRs to improve the project if you do decide to move forward with using the library!
